# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtview.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName("MplMainWindow")
        MplMainWindow.resize(909, 549)
        self.centralwidget = QtWidgets.QWidget(MplMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VLay_left_bar = QtWidgets.QVBoxLayout()
        self.VLay_left_bar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.VLay_left_bar.setSpacing(6)
        self.VLay_left_bar.setObjectName("VLay_left_bar")
        self.label_name_distribution = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_distribution.sizePolicy().hasHeightForWidth())
        self.label_name_distribution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_name_distribution.setFont(font)
        self.label_name_distribution.setAutoFillBackground(False)
        self.label_name_distribution.setStyleSheet("")
        self.label_name_distribution.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_distribution.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_distribution.setLineWidth(3)
        self.label_name_distribution.setTextFormat(QtCore.Qt.AutoText)
        self.label_name_distribution.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_distribution.setWordWrap(False)
        self.label_name_distribution.setIndent(-1)
        self.label_name_distribution.setOpenExternalLinks(False)
        self.label_name_distribution.setObjectName("label_name_distribution")
        self.VLay_left_bar.addWidget(self.label_name_distribution)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.VLay_left_bar.addWidget(self.line_2)
        self.HLay_distribution = QtWidgets.QGridLayout()
        self.HLay_distribution.setObjectName("HLay_distribution")
        self.LEdit_dist_burntime_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_burntime_min.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_burntime_min.setSizePolicy(sizePolicy)
        self.LEdit_dist_burntime_min.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_burntime_min.setObjectName("LEdit_dist_burntime_min")
        self.HLay_distribution.addWidget(self.LEdit_dist_burntime_min, 2, 3, 1, 1)
        self.LEdit_dist_burntime_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_burntime_max.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_burntime_max.setSizePolicy(sizePolicy)
        self.LEdit_dist_burntime_max.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_burntime_max.setObjectName("LEdit_dist_burntime_max")
        self.HLay_distribution.addWidget(self.LEdit_dist_burntime_max, 2, 1, 1, 1)
        self.label_burning_interval = QtWidgets.QLabel(self.centralwidget)
        self.label_burning_interval.setObjectName("label_burning_interval")
        self.HLay_distribution.addWidget(self.label_burning_interval, 2, 0, 1, 1)
        self.label_fire_interval = QtWidgets.QLabel(self.centralwidget)
        self.label_fire_interval.setObjectName("label_fire_interval")
        self.HLay_distribution.addWidget(self.label_fire_interval, 0, 0, 1, 1)
        self.LEdit_dist_fireinter_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_fireinter_min.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_fireinter_min.setSizePolicy(sizePolicy)
        self.LEdit_dist_fireinter_min.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_fireinter_min.setAcceptDrops(False)
        self.LEdit_dist_fireinter_min.setAutoFillBackground(False)
        self.LEdit_dist_fireinter_min.setMaxLength(15)
        self.LEdit_dist_fireinter_min.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LEdit_dist_fireinter_min.setDragEnabled(False)
        self.LEdit_dist_fireinter_min.setObjectName("LEdit_dist_fireinter_min")
        self.HLay_distribution.addWidget(self.LEdit_dist_fireinter_min, 0, 3, 1, 1)
        self.LEdit_dist_fireinter_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_fireinter_max.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_fireinter_max.setSizePolicy(sizePolicy)
        self.LEdit_dist_fireinter_max.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_fireinter_max.setMaxLength(15)
        self.LEdit_dist_fireinter_max.setObjectName("LEdit_dist_fireinter_max")
        self.HLay_distribution.addWidget(self.LEdit_dist_fireinter_max, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.HLay_distribution.addWidget(self.line_3, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.HLay_distribution.addWidget(self.line_4, 0, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.HLay_distribution.addWidget(self.line_5, 1, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.HLay_distribution.addWidget(self.line_6, 2, 2, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.HLay_distribution.addWidget(self.line_17, 1, 0, 1, 1)
        self.VLay_left_bar.addLayout(self.HLay_distribution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.VLay_left_bar.addItem(spacerItem)
        self.label_name_settings = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_settings.setFont(font)
        self.label_name_settings.setStyleSheet("")
        self.label_name_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_settings.setObjectName("label_name_settings")
        self.VLay_left_bar.addWidget(self.label_name_settings)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.VLay_left_bar.addWidget(self.line)
        self.GLay_settings = QtWidgets.QGridLayout()
        self.GLay_settings.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLay_settings.setObjectName("GLay_settings")
        self.label_total_fire_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_total_fire_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_total_fire_engines.setObjectName("label_total_fire_engines")
        self.GLay_settings.addWidget(self.label_total_fire_engines, 3, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.GLay_settings.addWidget(self.line_12, 10, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.GLay_settings.addWidget(self.line_7, 1, 0, 1, 1)
        self.label_time_of_modeling = QtWidgets.QLabel(self.centralwidget)
        self.label_time_of_modeling.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_of_modeling.setObjectName("label_time_of_modeling")
        self.GLay_settings.addWidget(self.label_time_of_modeling, 0, 0, 1, 1)
        self.LEdit_count_average_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_count_average_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_count_average_engines.setSizePolicy(sizePolicy)
        self.LEdit_count_average_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_count_average_engines.setObjectName("LEdit_count_average_engines")
        self.GLay_settings.addWidget(self.LEdit_count_average_engines, 7, 1, 1, 1)
        self.label_count_small_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_count_small_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_count_small_engines.setObjectName("label_count_small_engines")
        self.GLay_settings.addWidget(self.label_count_small_engines, 9, 0, 1, 1)
        self.label_count_big_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_count_big_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_count_big_engines.setObjectName("label_count_big_engines")
        self.GLay_settings.addWidget(self.label_count_big_engines, 5, 0, 1, 1)
        self.LEdit_total_fire_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_total_fire_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_total_fire_engines.setSizePolicy(sizePolicy)
        self.LEdit_total_fire_engines.setMinimumSize(QtCore.QSize(0, 0))
        self.LEdit_total_fire_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_total_fire_engines.setMaxLength(15)
        self.LEdit_total_fire_engines.setObjectName("LEdit_total_fire_engines")
        self.GLay_settings.addWidget(self.LEdit_total_fire_engines, 3, 1, 1, 1)
        self.LEdit_count_big_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_count_big_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_count_big_engines.setSizePolicy(sizePolicy)
        self.LEdit_count_big_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_count_big_engines.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LEdit_count_big_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LEdit_count_big_engines.setObjectName("LEdit_count_big_engines")
        self.GLay_settings.addWidget(self.LEdit_count_big_engines, 5, 1, 1, 1)
        self.label_count_average_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_count_average_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_count_average_engines.setObjectName("label_count_average_engines")
        self.GLay_settings.addWidget(self.label_count_average_engines, 7, 0, 1, 1)
        self.LEdit_count_small_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_count_small_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_count_small_engines.setSizePolicy(sizePolicy)
        self.LEdit_count_small_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_count_small_engines.setObjectName("LEdit_count_small_engines")
        self.GLay_settings.addWidget(self.LEdit_count_small_engines, 9, 1, 1, 1)
        self.LEdit_time_of_modeling = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_time_of_modeling.sizePolicy().hasHeightForWidth())
        self.LEdit_time_of_modeling.setSizePolicy(sizePolicy)
        self.LEdit_time_of_modeling.setMinimumSize(QtCore.QSize(0, 0))
        self.LEdit_time_of_modeling.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_time_of_modeling.setAutoFillBackground(False)
        self.LEdit_time_of_modeling.setStyleSheet("")
        self.LEdit_time_of_modeling.setInputMask("")
        self.LEdit_time_of_modeling.setText("")
        self.LEdit_time_of_modeling.setMaxLength(15)
        self.LEdit_time_of_modeling.setClearButtonEnabled(False)
        self.LEdit_time_of_modeling.setObjectName("LEdit_time_of_modeling")
        self.GLay_settings.addWidget(self.LEdit_time_of_modeling, 0, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.GLay_settings.addWidget(self.line_9, 4, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.GLay_settings.addWidget(self.line_8, 1, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.GLay_settings.addWidget(self.line_11, 8, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.GLay_settings.addWidget(self.line_10, 6, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.GLay_settings.addWidget(self.line_13, 4, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.GLay_settings.addWidget(self.line_14, 6, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.GLay_settings.addWidget(self.line_15, 8, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.GLay_settings.addWidget(self.line_16, 10, 1, 1, 1)
        self.VLay_left_bar.addLayout(self.GLay_settings)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLay_left_bar.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.VLay_left_bar)
        self.VLay_right_bar = QtWidgets.QVBoxLayout()
        self.VLay_right_bar.setObjectName("VLay_right_bar")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_test)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.VLay_tabtest_graph = QtWidgets.QVBoxLayout()
        self.VLay_tabtest_graph.setObjectName("VLay_tabtest_graph")
        self.mpl = MplWidget(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.VLay_tabtest_graph.addWidget(self.mpl)
        self.button_start_test = QtWidgets.QPushButton(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_test.sizePolicy().hasHeightForWidth())
        self.button_start_test.setSizePolicy(sizePolicy)
        self.button_start_test.setObjectName("button_start_test")
        self.VLay_tabtest_graph.addWidget(self.button_start_test, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addLayout(self.VLay_tabtest_graph)
        self.tabWidget.addTab(self.tab_test, "")
        self.tab_stat = QtWidgets.QWidget()
        self.tab_stat.setObjectName("tab_stat")
        self.tabWidget.addTab(self.tab_stat, "")
        self.VLay_right_bar.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.VLay_right_bar)
        MplMainWindow.setCentralWidget(self.centralwidget)
        self.mplmenuBar = QtWidgets.QMenuBar(MplMainWindow)
        self.mplmenuBar.setGeometry(QtCore.QRect(0, 0, 909, 30))
        self.mplmenuBar.setObjectName("mplmenuBar")
        self.mplmenuFile = QtWidgets.QMenu(self.mplmenuBar)
        self.mplmenuFile.setObjectName("mplmenuFile")
        MplMainWindow.setMenuBar(self.mplmenuBar)
        self.mplactionOpen = QtWidgets.QAction(MplMainWindow)
        self.mplactionOpen.setObjectName("mplactionOpen")
        self.mplactionQuit = QtWidgets.QAction(MplMainWindow)
        self.mplactionQuit.setObjectName("mplactionQuit")
        self.mplmenuFile.addAction(self.mplactionOpen)
        self.mplmenuFile.addAction(self.mplactionQuit)
        self.mplmenuBar.addAction(self.mplmenuFile.menuAction())

        self.retranslateUi(MplMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "MainWindow"))
        self.label_name_distribution.setText(_translate("MplMainWindow", "Uniform distribution"))
        self.LEdit_dist_burntime_min.setPlaceholderText(_translate("MplMainWindow", "Min"))
        self.LEdit_dist_burntime_max.setPlaceholderText(_translate("MplMainWindow", "Max"))
        self.label_burning_interval.setText(_translate("MplMainWindow", "Burning time"))
        self.label_fire_interval.setText(_translate("MplMainWindow", "Fire interval"))
        self.LEdit_dist_fireinter_min.setPlaceholderText(_translate("MplMainWindow", "Min"))
        self.LEdit_dist_fireinter_max.setPlaceholderText(_translate("MplMainWindow", "Max"))
        self.label_name_settings.setText(_translate("MplMainWindow", "Model Settings"))
        self.label_total_fire_engines.setText(_translate("MplMainWindow", "Total fire engines"))
        self.label_time_of_modeling.setText(_translate("MplMainWindow", "Time of modeling"))
        self.LEdit_count_average_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.label_count_small_engines.setText(_translate("MplMainWindow", "Small fire engines"))
        self.label_count_big_engines.setText(_translate("MplMainWindow", "Big fire engines"))
        self.LEdit_total_fire_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.LEdit_count_big_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.label_count_average_engines.setText(_translate("MplMainWindow", "Average fire engines"))
        self.LEdit_count_small_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.LEdit_time_of_modeling.setPlaceholderText(_translate("MplMainWindow", "Second"))
        self.button_start_test.setText(_translate("MplMainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("MplMainWindow", "Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stat), _translate("MplMainWindow", "Tab 2"))
        self.mplmenuFile.setTitle(_translate("MplMainWindow", "Fi&le"))
        self.mplactionOpen.setText(_translate("MplMainWindow", "&Open"))
        self.mplactionQuit.setText(_translate("MplMainWindow", "&Quit"))


from .mplwidget import MplWidget
