# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/qtview.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName("MplMainWindow")
        MplMainWindow.resize(938, 634)
        self.centralwidget = QtWidgets.QWidget(MplMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VLay_left_bar = QtWidgets.QVBoxLayout()
        self.VLay_left_bar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.VLay_left_bar.setSpacing(6)
        self.VLay_left_bar.setObjectName("VLay_left_bar")
        self.label_name_distribution_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_distribution_2.sizePolicy().hasHeightForWidth())
        self.label_name_distribution_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_name_distribution_2.setFont(font)
        self.label_name_distribution_2.setAutoFillBackground(False)
        self.label_name_distribution_2.setStyleSheet("")
        self.label_name_distribution_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_distribution_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_distribution_2.setLineWidth(3)
        self.label_name_distribution_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_name_distribution_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_distribution_2.setWordWrap(False)
        self.label_name_distribution_2.setIndent(-1)
        self.label_name_distribution_2.setOpenExternalLinks(False)
        self.label_name_distribution_2.setObjectName("label_name_distribution_2")
        self.VLay_left_bar.addWidget(self.label_name_distribution_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.VLay_left_bar.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LEdit_dist_fireinter_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_fireinter_max.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_fireinter_max.setSizePolicy(sizePolicy)
        self.LEdit_dist_fireinter_max.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_fireinter_max.setMaxLength(8)
        self.LEdit_dist_fireinter_max.setObjectName("LEdit_dist_fireinter_max")
        self.gridLayout.addWidget(self.LEdit_dist_fireinter_max, 1, 1, 1, 1)
        self.label_fire_interval = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fire_interval.sizePolicy().hasHeightForWidth())
        self.label_fire_interval.setSizePolicy(sizePolicy)
        self.label_fire_interval.setObjectName("label_fire_interval")
        self.gridLayout.addWidget(self.label_fire_interval, 1, 0, 1, 1)
        self.VLay_left_bar.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.VLay_left_bar.addItem(spacerItem)
        self.label_name_distribution = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_distribution.sizePolicy().hasHeightForWidth())
        self.label_name_distribution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_name_distribution.setFont(font)
        self.label_name_distribution.setAutoFillBackground(False)
        self.label_name_distribution.setStyleSheet("")
        self.label_name_distribution.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_distribution.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_distribution.setLineWidth(3)
        self.label_name_distribution.setTextFormat(QtCore.Qt.AutoText)
        self.label_name_distribution.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_distribution.setWordWrap(False)
        self.label_name_distribution.setIndent(-1)
        self.label_name_distribution.setOpenExternalLinks(False)
        self.label_name_distribution.setObjectName("label_name_distribution")
        self.VLay_left_bar.addWidget(self.label_name_distribution)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.VLay_left_bar.addWidget(self.line_3)
        self.HLay_distribution = QtWidgets.QGridLayout()
        self.HLay_distribution.setObjectName("HLay_distribution")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.HLay_distribution.addWidget(self.line_18, 3, 2, 1, 1)
        self.LEdit_dist_burntime_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_burntime_min.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_burntime_min.setSizePolicy(sizePolicy)
        self.LEdit_dist_burntime_min.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_burntime_min.setMaxLength(8)
        self.LEdit_dist_burntime_min.setObjectName("LEdit_dist_burntime_min")
        self.HLay_distribution.addWidget(self.LEdit_dist_burntime_min, 1, 3, 1, 1)
        self.LEdit_dist_burntime_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_burntime_max.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_burntime_max.setSizePolicy(sizePolicy)
        self.LEdit_dist_burntime_max.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_burntime_max.setMaxLength(8)
        self.LEdit_dist_burntime_max.setObjectName("LEdit_dist_burntime_max")
        self.HLay_distribution.addWidget(self.LEdit_dist_burntime_max, 1, 1, 1, 1)
        self.label_burning_interval = QtWidgets.QLabel(self.centralwidget)
        self.label_burning_interval.setObjectName("label_burning_interval")
        self.HLay_distribution.addWidget(self.label_burning_interval, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.HLay_distribution.addWidget(self.line_4, 0, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.HLay_distribution.addWidget(self.line_6, 1, 2, 1, 1)
        self.LEdit_dist_service_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_service_min.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_service_min.setSizePolicy(sizePolicy)
        self.LEdit_dist_service_min.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_service_min.setMaxLength(8)
        self.LEdit_dist_service_min.setObjectName("LEdit_dist_service_min")
        self.HLay_distribution.addWidget(self.LEdit_dist_service_min, 3, 3, 1, 1)
        self.label_service_time = QtWidgets.QLabel(self.centralwidget)
        self.label_service_time.setObjectName("label_service_time")
        self.HLay_distribution.addWidget(self.label_service_time, 3, 0, 1, 1)
        self.LEdit_dist_service_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_dist_service_max.sizePolicy().hasHeightForWidth())
        self.LEdit_dist_service_max.setSizePolicy(sizePolicy)
        self.LEdit_dist_service_max.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_dist_service_max.setMaxLength(8)
        self.LEdit_dist_service_max.setObjectName("LEdit_dist_service_max")
        self.HLay_distribution.addWidget(self.LEdit_dist_service_max, 3, 1, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.HLay_distribution.addWidget(self.line_19, 2, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.HLay_distribution.addWidget(self.line_20, 2, 1, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.HLay_distribution.addWidget(self.line_21, 2, 3, 1, 1)
        self.VLay_left_bar.addLayout(self.HLay_distribution)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.VLay_left_bar.addItem(spacerItem1)
        self.label_name_settings = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_settings.setFont(font)
        self.label_name_settings.setStyleSheet("")
        self.label_name_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_settings.setObjectName("label_name_settings")
        self.VLay_left_bar.addWidget(self.label_name_settings)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.VLay_left_bar.addWidget(self.line)
        self.GLay_settings = QtWidgets.QGridLayout()
        self.GLay_settings.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLay_settings.setObjectName("GLay_settings")
        self.label_total_fire_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_total_fire_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_total_fire_engines.setObjectName("label_total_fire_engines")
        self.GLay_settings.addWidget(self.label_total_fire_engines, 3, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.GLay_settings.addWidget(self.line_12, 13, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.GLay_settings.addWidget(self.line_7, 1, 0, 1, 1)
        self.label_time_of_modeling = QtWidgets.QLabel(self.centralwidget)
        self.label_time_of_modeling.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_of_modeling.setObjectName("label_time_of_modeling")
        self.GLay_settings.addWidget(self.label_time_of_modeling, 0, 0, 1, 1)
        self.LEdit_count_average_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_count_average_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_count_average_engines.setSizePolicy(sizePolicy)
        self.LEdit_count_average_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_count_average_engines.setObjectName("LEdit_count_average_engines")
        self.GLay_settings.addWidget(self.LEdit_count_average_engines, 7, 1, 1, 1)
        self.label_count_small_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_count_small_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_count_small_engines.setObjectName("label_count_small_engines")
        self.GLay_settings.addWidget(self.label_count_small_engines, 9, 0, 1, 1)
        self.label_count_big_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_count_big_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_count_big_engines.setObjectName("label_count_big_engines")
        self.GLay_settings.addWidget(self.label_count_big_engines, 5, 0, 1, 1)
        self.LEdit_total_fire_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_total_fire_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_total_fire_engines.setSizePolicy(sizePolicy)
        self.LEdit_total_fire_engines.setMinimumSize(QtCore.QSize(0, 0))
        self.LEdit_total_fire_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_total_fire_engines.setMaxLength(15)
        self.LEdit_total_fire_engines.setObjectName("LEdit_total_fire_engines")
        self.GLay_settings.addWidget(self.LEdit_total_fire_engines, 3, 1, 1, 1)
        self.LEdit_count_big_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_count_big_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_count_big_engines.setSizePolicy(sizePolicy)
        self.LEdit_count_big_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_count_big_engines.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LEdit_count_big_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LEdit_count_big_engines.setObjectName("LEdit_count_big_engines")
        self.GLay_settings.addWidget(self.LEdit_count_big_engines, 5, 1, 1, 1)
        self.label_count_average_engines = QtWidgets.QLabel(self.centralwidget)
        self.label_count_average_engines.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_count_average_engines.setObjectName("label_count_average_engines")
        self.GLay_settings.addWidget(self.label_count_average_engines, 7, 0, 1, 1)
        self.LEdit_count_small_engines = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_count_small_engines.sizePolicy().hasHeightForWidth())
        self.LEdit_count_small_engines.setSizePolicy(sizePolicy)
        self.LEdit_count_small_engines.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_count_small_engines.setObjectName("LEdit_count_small_engines")
        self.GLay_settings.addWidget(self.LEdit_count_small_engines, 9, 1, 1, 1)
        self.LEdit_time_of_modeling = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEdit_time_of_modeling.sizePolicy().hasHeightForWidth())
        self.LEdit_time_of_modeling.setSizePolicy(sizePolicy)
        self.LEdit_time_of_modeling.setMinimumSize(QtCore.QSize(0, 0))
        self.LEdit_time_of_modeling.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LEdit_time_of_modeling.setAutoFillBackground(False)
        self.LEdit_time_of_modeling.setStyleSheet("")
        self.LEdit_time_of_modeling.setInputMask("")
        self.LEdit_time_of_modeling.setText("")
        self.LEdit_time_of_modeling.setMaxLength(15)
        self.LEdit_time_of_modeling.setClearButtonEnabled(False)
        self.LEdit_time_of_modeling.setObjectName("LEdit_time_of_modeling")
        self.GLay_settings.addWidget(self.LEdit_time_of_modeling, 0, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.GLay_settings.addWidget(self.line_9, 4, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.GLay_settings.addWidget(self.line_8, 1, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.GLay_settings.addWidget(self.line_11, 8, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.GLay_settings.addWidget(self.line_10, 6, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.GLay_settings.addWidget(self.line_13, 4, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.GLay_settings.addWidget(self.line_14, 6, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.GLay_settings.addWidget(self.line_15, 8, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.GLay_settings.addWidget(self.line_16, 13, 1, 1, 1)
        self.VLay_left_bar.addLayout(self.GLay_settings)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.VLay_left_bar.addItem(spacerItem2)
        self.button_start_test = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start_test.sizePolicy().hasHeightForWidth())
        self.button_start_test.setSizePolicy(sizePolicy)
        self.button_start_test.setMinimumSize(QtCore.QSize(0, 75))
        self.button_start_test.setObjectName("button_start_test")
        self.VLay_left_bar.addWidget(self.button_start_test)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLay_left_bar.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.VLay_left_bar)
        self.VLay_right_bar = QtWidgets.QVBoxLayout()
        self.VLay_right_bar.setObjectName("VLay_right_bar")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_test)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.VLay_tabtest_graph = QtWidgets.QVBoxLayout()
        self.VLay_tabtest_graph.setObjectName("VLay_tabtest_graph")
        self.mpl = MplWidget(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.VLay_tabtest_graph.addWidget(self.mpl)
        self.verticalLayout_4.addLayout(self.VLay_tabtest_graph)
        self.tabWidget.addTab(self.tab_test, "")
        self.tab_stat = QtWidgets.QWidget()
        self.tab_stat.setObjectName("tab_stat")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_stat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VLay_tabtest_graph_2 = QtWidgets.QVBoxLayout()
        self.VLay_tabtest_graph_2.setObjectName("VLay_tabtest_graph_2")
        self.mpl_stat = MplStatWidget(self.tab_stat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_stat.sizePolicy().hasHeightForWidth())
        self.mpl_stat.setSizePolicy(sizePolicy)
        self.mpl_stat.setObjectName("mpl_stat")
        self.VLay_tabtest_graph_2.addWidget(self.mpl_stat)
        self.verticalLayout.addLayout(self.VLay_tabtest_graph_2)
        self.tabWidget.addTab(self.tab_stat, "")
        self.VLay_right_bar.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.VLay_right_bar)
        MplMainWindow.setCentralWidget(self.centralwidget)
        self.mplmenuBar = QtWidgets.QMenuBar(MplMainWindow)
        self.mplmenuBar.setGeometry(QtCore.QRect(0, 0, 938, 30))
        self.mplmenuBar.setObjectName("mplmenuBar")
        self.mplmenuFile = QtWidgets.QMenu(self.mplmenuBar)
        self.mplmenuFile.setObjectName("mplmenuFile")
        MplMainWindow.setMenuBar(self.mplmenuBar)
        self.mplactionOpen = QtWidgets.QAction(MplMainWindow)
        self.mplactionOpen.setObjectName("mplactionOpen")
        self.mplactionQuit = QtWidgets.QAction(MplMainWindow)
        self.mplactionQuit.setObjectName("mplactionQuit")
        self.mplmenuFile.addAction(self.mplactionOpen)
        self.mplmenuFile.addAction(self.mplactionQuit)
        self.mplmenuBar.addAction(self.mplmenuFile.menuAction())

        self.retranslateUi(MplMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "MainWindow"))
        self.label_name_distribution_2.setText(_translate("MplMainWindow", "Exponential distribution"))
        self.LEdit_dist_fireinter_max.setPlaceholderText(_translate("MplMainWindow", "Average"))
        self.label_fire_interval.setText(_translate("MplMainWindow", "Fire interval"))
        self.label_name_distribution.setText(_translate("MplMainWindow", "Uniform distribution"))
        self.LEdit_dist_burntime_min.setPlaceholderText(_translate("MplMainWindow", "Min"))
        self.LEdit_dist_burntime_max.setPlaceholderText(_translate("MplMainWindow", "Max"))
        self.label_burning_interval.setText(_translate("MplMainWindow", "Burning time"))
        self.LEdit_dist_service_min.setPlaceholderText(_translate("MplMainWindow", "Min"))
        self.label_service_time.setText(_translate("MplMainWindow", "Service time"))
        self.LEdit_dist_service_max.setPlaceholderText(_translate("MplMainWindow", "Max"))
        self.label_name_settings.setText(_translate("MplMainWindow", "Model Settings"))
        self.label_total_fire_engines.setText(_translate("MplMainWindow", "Total fire engines"))
        self.label_time_of_modeling.setText(_translate("MplMainWindow", "Time of modeling"))
        self.LEdit_count_average_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.label_count_small_engines.setText(_translate("MplMainWindow", "Small fire engines"))
        self.label_count_big_engines.setText(_translate("MplMainWindow", "Big fire engines"))
        self.LEdit_total_fire_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.LEdit_count_big_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.label_count_average_engines.setText(_translate("MplMainWindow", "Average fire engines"))
        self.LEdit_count_small_engines.setPlaceholderText(_translate("MplMainWindow", "Count"))
        self.LEdit_time_of_modeling.setPlaceholderText(_translate("MplMainWindow", "Second"))
        self.button_start_test.setText(_translate("MplMainWindow", "Start"))
        self.plainTextEdit.setPlainText(_translate("MplMainWindow", "ТЕХНІЧНЕ ЗАВДАННЯ\n"
"\n"
"на виконання розрахунково-графічної роботи з дисципліни «Моделювання»\n"
"    Тема: Моделювання пожежної частини, Варіант « Diablo»\n"
"    Виконавці: Камак М.Д., Демешко А.С., Патай А.В,, КІ-162.\n"
"    Опис системи\n"
"У місті Дьябло часто трапляються пожежі. Сигнал про пожежу надходить у пожежну частину й на гасіння пожежі виїжджає кілька пожежних машин. Якщо всі машини виїдуть на пожежу, то може виявитися, що іншу пожежу не буде кому гасити. Машини виїжджають, якщо вони є й готові до гасіння. Інформація про те, що пожежа закінчилася, не надходить, тому машина їде на пожежу у будь якому разі. Прибувши на пожежу, пожежні починають гасити її, у результаті чого час горіння й, відповідно, збитки від пожежі скорочуються. Але якщо машин мало, те засобів пожежегасіння може не вистачити, і тоді виявиться, що поїздка на пожежу була марною. Якщо пожежа вже догоріла, то машина відразу ж їде назад. Після повернення в пожежну частину машина проходить техобслуговування, після чого знову готова до гасіння. \n"
"    Завдання на проектування \n"
"    Створити Python застосування для імітаційного моделювання авіаперевезень, яке дозволить:\n"
"    - налаштування параметрів моделі, а саме: кiлькiсть пожежних машин, кількість балів пожежі , кількість балів пожежної машини, час моделювання;\n"
"    - проведення тестових запусків моделі при різних налаштуваннях з динамічною індикацією кількості машин на пожежній станції, довжини черги пожеж, кількість працюючих машин та кількість машин на технічне обслуговування та можливості виведення протоколу роботи моделі під час тестових запусків;\n"
"    - проведення експериментів для отримання статистичних характеристик для довжини черги пожеж.\n"
"\n"
"Обсяг текстової документації\n"
"Робота обсягом 10-15 с. формату А4\n"
"Орієнтовна трудомісткість роботи  –  36 людино-годин.\n"
"Дата представлення роботи  –  останній тиждень 2-го семестру\n"
"\n"
"Керівник роботи    \n"
"доцент     Пріла О.А.\n"
"«21» лютого 2019 р. "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MplMainWindow", "Technical Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("MplMainWindow", "Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stat), _translate("MplMainWindow", "Stat"))
        self.mplmenuFile.setTitle(_translate("MplMainWindow", "Fi&le"))
        self.mplactionOpen.setText(_translate("MplMainWindow", "&Open"))
        self.mplactionQuit.setText(_translate("MplMainWindow", "&Quit"))


from .mplstatwidget import MplStatWidget
from .mplwidget import MplWidget
